version: "0.2"
language: en
ignorePaths:
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - package.json
dictionaryDefinitions: null
dictionaries: null
enableCompoundWords: true
words:
  - amet
  - Atts
  - brotli
  - clazz
  - Consolas
  - deslugify
  - fnames
  - gzipped
  - Logix
  - noopener
  - Noto
  - OAGS
  - pako
  - Segoe
  - splunges
  - srgb
  - Tweens
import: null
ignoreWords: null
